INFERANALYZE= /usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/bin/InferAnalyze -results_dir '/Users/Lucas/Git/ASEApp/infer-out'

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/Lucas/Git/ASEApp/infer-out/captured/AlarmReceiver.java.095dd84647507586b60983f6cdf51649
cl1: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl1.cluster >cl1

#/Users/Lucas/Git/ASEApp/infer-out/captured/BuildConfig.java.978e183df2468ef60182e3b43826b83d
cl2: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl2.cluster >cl2

#/Users/Lucas/Git/ASEApp/infer-out/captured/BuildConfig.java.a009b1619b83cbf6c019e2c571704f26
cl3: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl3.cluster >cl3

#/Users/Lucas/Git/ASEApp/infer-out/captured/CameraActivity.java.70373e20c40903be8cf27f67c16422bc
cl4: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl4.cluster >cl4

#/Users/Lucas/Git/ASEApp/infer-out/captured/ContactServer.java.c0562ee9dd5a170ee896e378c8e779f8
cl5: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl5.cluster >cl5

#/Users/Lucas/Git/ASEApp/infer-out/captured/ExampleUnitTest.java.0b6bc06d1a76dc20df8c052d000ade06
cl6: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl6.cluster >cl6

#/Users/Lucas/Git/ASEApp/infer-out/captured/HeatMapData.java.6549786c0a3ce120c96cc3e7dbf69472
cl7: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl7.cluster >cl7

#/Users/Lucas/Git/ASEApp/infer-out/captured/Manifest.java.30bc4c1cfee4015610fa988d96324665
cl8: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl8.cluster >cl8

#/Users/Lucas/Git/ASEApp/infer-out/captured/Manifest.java.c0da29091b8030b630b25a78e6a78f5b
cl9: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl9.cluster >cl9

#/Users/Lucas/Git/ASEApp/infer-out/captured/MapsActivity.java.e6433ecb5ecc0b04483f3f99318da8b6
cl10: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl10.cluster >cl10

#/Users/Lucas/Git/ASEApp/infer-out/captured/MapsActivityTest.java.dcc4b2d2b3a63f5758f8d4d85078a364
cl11: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl11.cluster >cl11

#/Users/Lucas/Git/ASEApp/infer-out/captured/MenuActivity.java.262bc40fc5d411aff5b0a937b3f1119f
cl12: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl12.cluster >cl12

#/Users/Lucas/Git/ASEApp/infer-out/captured/MenuActivityTest.java.40414e43d90e15795dcec281f4cb514d
cl13: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl13.cluster >cl13

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.00623da99c4d1403de190ecd94551727
cl14: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl14.cluster >cl14

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.062a933c5ca066811786814d7389a726
cl15: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl15.cluster >cl15

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.21f2d72126b640418e8c48ff9f86ed7d
cl16: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl16.cluster >cl16

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.40d4e3219c3488f2ae233e42c85a249e
cl17: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl17.cluster >cl17

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.4d6b9cece30f1cb3978e3b3a891aa7b4
cl18: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl18.cluster >cl18

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.5eba1214995c3f80cb0bd653be72aae7
cl19: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl19.cluster >cl19

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.7e558cf86703f0d0072b1c9815b7e6c5
cl20: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl20.cluster >cl20

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.8b7cb4350c63f71a1c7a3f0f2cef4d02
cl21: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl21.cluster >cl21

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl22: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl22.cluster >cl22

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.dcee548589e1bd56be954c70ebcd755d
cl23: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl23.cluster >cl23

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.ed2872b26942afa5a8f13a8f68c107c1
cl24: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl24.cluster >cl24

#/Users/Lucas/Git/ASEApp/infer-out/captured/R.java.f7b591976fb4dfac23f1f0138fa4b2ef
cl25: 
	$(INFERANALYZE) -cluster /Users/Lucas/Git/ASEApp/infer-out/multicore/xcl25.cluster >cl25


clean:
	rm -f $(CLUSTERS)
